version: '3.8'

services:
  devopsdb:
    image: kolasurendra/ourproject:db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure

  application:
    image: kolasurendra/ourproject:app
    ports:
      - "1234:8080"
    depends_on:
      - devopsdb
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure

volumes:
  db_data:
